apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nodejs-ihembgmj
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/nodejs-ihembgmj:b851f585b533b210bce4ef7de42f5bee1070c629@sha256:97b6f7899d84b53478c008c3fe3ed7222d51f313e67c0c92eff87e14587cae60
          name: container-image
