apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nodejs-ihembgmj
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/nodejs-ihembgmj:37b433e2eefc7b46a56f076ab848c78bdf15e546@sha256:a514766c1d816ca7d85a594bdbb7ac7ad9e8f16dc3c208cdd31a3ef373628aa1
          name: container-image
